name: persistences_types_3aojr
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  floor: ^1.4.2
  firebase_core: ^2.20.0
  cloud_firestore: ^4.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/firebase.png
    - assets/floor.png
